import "./globals.css";
import { philosopher } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${philosopher.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
