import './globals.css';
import { Header, Footer } from '@/components/layout';
import { philosopher } from '@/lib/fonts';

export const metadata = {
  title: "Aran Doncel Photography",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth scroll-pt-16">
      <body className={`${philosopher.className} antialiased`}>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
